version: '3'
services:
  web:
    container_name: django-docker
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    working_dir: /code
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    container_name: django-docker-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'forum_data'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'INOtahi1210'
      MYSQL_ALLOW_EMPTY_PASSWORD: ‘yes’
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306


