# Generated by Django 3.1.7 on 2021-04-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0004_auto_20210330_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='reference_book_name',
            field=models.CharField(max_length=30, null=True, verbose_name='参考書名'),
        ),
        migrations.AddField(
            model_name='topic',
            name='reference_book_page',
            field=models.IntegerField(blank=True, null=True, verbose_name='ページ'),
        ),
    ]
