# Generated by Django 3.1.7 on 2021-04-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0005_auto_20210412_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='画像アップロード'),
        ),
    ]
