# Generated by Django 3.1.7 on 2021-04-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0006_topic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='画像アップロード'),
        ),
    ]
